/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Siswa, Pelanggaran, Kehadiran, BimbinganLog, JadwalKonseling } from './types';

export const INITIAL_SISWA: Siswa[] = [
  {
    id: 's1',
    nama: 'Aditya Pratama',
    nisn: '0081234561',
    kelas: 'XI-IPA-1',
    status: 'Aktif',
    fotoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=200',
    ttl: 'Jakarta, 12 April 2009',
    alamat: 'Jl. Merdeka No. 45, Jakarta Pusat',
    noHp: '0812-3456-7890',
    namaOrtu: 'Bambang Pratama',
    pekerjaanOrtu: 'Wiraswasta',
    kontakDarurat: '0812-3456-7890 (Ayah)',
    riwayatMedis: 'Alergi debu ringan, tidak ada penyakit kronis.',
    totalPoin: 15,
  },
  {
    id: 's2',
    nama: 'Budi Santoso',
    nisn: '0081234562',
    kelas: 'XI-IPA-1',
    status: 'Aktif',
    fotoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=200',
    ttl: 'Bandung, 30 September 2008',
    alamat: 'Jl. Melati Raya No. 12, Jakarta Barat',
    noHp: '0813-9876-5432',
    namaOrtu: 'Joko Santoso',
    pekerjaanOrtu: 'Pegawai Negeri Sipil (PNS)',
    kontakDarurat: '0813-9876-5432 (Ayah)',
    riwayatMedis: 'Menggunakan kacamata minus 2.5.',
    totalPoin: 110, // Diatas 100 poin, memicu peringatan (SP1/SP2)
  },
  {
    id: 's3',
    nama: 'Cantika Putri',
    nisn: '0081234563',
    kelas: 'XI-IPS-2',
    status: 'Aktif',
    fotoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200',
    ttl: 'Surabaya, 5 Juni 2009',
    alamat: 'Apartemen Kebon Jeruk, Tower B-10',
    noHp: '0857-1122-3344',
    namaOrtu: 'Dewi Lestari (Ibu)',
    pekerjaanOrtu: 'Ibu Rumah Tangga',
    kontakDarurat: '0857-1122-3344 (Ibu)',
    riwayatMedis: 'Pernah asma saat kecil, membawa inhaler pribadi.',
    totalPoin: 0,
  },
  {
    id: 's4',
    nama: 'Dedi Kurniawan',
    nisn: '0081234564',
    kelas: 'XI-IPA-1',
    status: 'Aktif',
    fotoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    ttl: 'Solo, 21 November 2008',
    alamat: 'Jl. Mawar Merah No. 88, Jakarta Pusat',
    noHp: '0821-2233-4455',
    namaOrtu: 'Hadi Kurniawan',
    pekerjaanOrtu: 'Karyawan Swasta',
    kontakDarurat: '0821-2233-4455 (Ayah)',
    riwayatMedis: 'Tidak ada riwayat medis khusus.',
    totalPoin: 45,
  },
  {
    id: 's5',
    nama: 'Eka Lestari',
    nisn: '0081234565',
    kelas: 'XII-IPA-2',
    status: 'Aktif',
    fotoUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=200',
    ttl: 'Yogyakarta, 1 Januari 2008',
    alamat: 'Perumahan Indah Permai Blok C/4',
    noHp: '0812-9900-8877',
    namaOrtu: 'Rudy Hartono',
    pekerjaanOrtu: 'Dosen',
    kontakDarurat: '0812-9900-8877 (Ayah)',
    riwayatMedis: 'Alergi makanan laut (seafood).',
    totalPoin: 5,
  },
  {
    id: 's6',
    nama: 'Farhan Ramadhan',
    nisn: '0081234566',
    kelas: 'XI-IPS-2',
    status: 'Aktif',
    fotoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    ttl: 'Medan, 17 Agustus 2008',
    alamat: 'Jl. Kenanga Timur No. 17, Jakarta Barat',
    noHp: '0813-4455-6677',
    namaOrtu: 'Syarif Ramadhan',
    pekerjaanOrtu: 'Pedagang',
    kontakDarurat: '0813-4455-6677 (Ayah)',
    riwayatMedis: 'Tidak ada catatan penyakit khusus.',
    totalPoin: 80, // Poin tinggi hampir menyentuh SP1
  },
  {
    id: 's7',
    nama: 'Gita Safitri',
    nisn: '0081234567',
    kelas: 'X-A',
    status: 'Aktif',
    fotoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    ttl: 'Semarang, 10 Maret 2010',
    alamat: 'Perum Gading Elok Blok F/12',
    noHp: '0858-7766-5544',
    namaOrtu: 'Wawan Safitri',
    pekerjaanOrtu: 'Arsitek',
    kontakDarurat: '0858-7766-5544 (Ayah)',
    riwayatMedis: 'Sehat walafiat.',
    totalPoin: 0,
  },
  {
    id: 's8',
    nama: 'Hendra Wijaya',
    nisn: '0081234568',
    kelas: 'X-B',
    status: 'Aktif',
    fotoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=200',
    ttl: 'Jakarta, 19 Juli 2010',
    alamat: 'Jl. Diponegoro No. 34, Jakarta Pusat',
    noHp: '0811-2233-9900',
    namaOrtu: 'Agus Wijaya',
    pekerjaanOrtu: 'TNI-AD',
    kontakDarurat: '0811-2233-9900 (Ayah)',
    riwayatMedis: 'Pernah patah pergelangan tangan kiri (sudah sembuh total).',
    totalPoin: 50,
  }
];

export const INITIAL_PELANGGARAN: Pelanggaran[] = [
  {
    id: 'p1',
    siswaId: 's2',
    namaSiswa: 'Budi Santoso',
    kelasSiswa: 'XI-IPA-1',
    tanggal: '2026-06-15',
    jenis: 'Tindakan Bullying (Perundungan)',
    poin: 100,
    catatan: 'Melakukan intimidasi verbal pada adik kelas X di kantin belakang.',
  },
  {
    id: 'p2',
    siswaId: 's2',
    namaSiswa: 'Budi Santoso',
    kelasSiswa: 'XI-IPA-1',
    tanggal: '2026-06-20',
    jenis: 'Tidak Masuk Tanpa Keterangan (Alpa)',
    poin: 10,
    catatan: 'Meninggalkan sekolah tanpa izin setelah istirahat pertama.',
  },
  {
    id: 'p3',
    siswaId: 's1',
    namaSiswa: 'Aditya Pratama',
    kelasSiswa: 'XI-IPA-1',
    tanggal: '2026-06-22',
    jenis: 'Terlambat Masuk Sekolah',
    poin: 5,
    catatan: 'Terlambat 15 menit dengan alasan ban sepeda bocor.',
  },
  {
    id: 'p4',
    siswaId: 's1',
    namaSiswa: 'Aditya Pratama',
    kelasSiswa: 'XI-IPA-1',
    tanggal: '2026-06-24',
    jenis: 'Membawa / Bermain HP di Kelas Saat KBM',
    poin: 10,
    catatan: 'Menggunakan handphone di kolong meja saat mata pelajaran Sejarah.',
  },
  {
    id: 'p5',
    siswaId: 's4',
    namaSiswa: 'Dedi Kurniawan',
    kelasSiswa: 'XI-IPA-1',
    tanggal: '2026-06-25',
    jenis: 'Keluar Kelas Tanpa Izin (Bolos Jam Pelajaran)',
    poin: 15,
    catatan: 'Bolos jam pelajaran Kimia kedua, ditemukan di area kantin luar.',
  },
  {
    id: 'p6',
    siswaId: 's4',
    namaSiswa: 'Dedi Kurniawan',
    kelasSiswa: 'XI-IPA-1',
    tanggal: '2026-07-02',
    jenis: 'Tidak Masuk Tanpa Keterangan (Alpa)',
    poin: 10,
    catatan: 'Absen tanpa ada surat izin maupun kabar dari orang tua.',
  },
  {
    id: 'p7',
    siswaId: 's4',
    namaSiswa: 'Dedi Kurniawan',
    kelasSiswa: 'XI-IPA-1',
    tanggal: '2026-07-03',
    jenis: 'Tidak Masuk Tanpa Keterangan (Alpa)',
    poin: 10,
    catatan: 'Absen beruntun hari kedua tanpa kejelasan.',
  },
  {
    id: 'p8',
    siswaId: 's4',
    namaSiswa: 'Dedi Kurniawan',
    kelasSiswa: 'XI-IPA-1',
    tanggal: '2026-07-04',
    jenis: 'Tidak Masuk Tanpa Keterangan (Alpa)',
    poin: 10,
    catatan: 'Absen beruntun hari ketiga. Perlu tindak lanjut pemanggilan orang tua.',
  },
  {
    id: 'p9',
    siswaId: 's6',
    namaSiswa: 'Farhan Ramadhan',
    kelasSiswa: 'XI-IPS-2',
    tanggal: '2026-06-28',
    jenis: 'Merokok di Lingkungan Sekolah',
    poin: 50,
    catatan: 'Kedapatan membawa dan menghisap rokok elektrik (vape) di toilet siswa.',
  },
  {
    id: 'p10',
    siswaId: 's6',
    namaSiswa: 'Farhan Ramadhan',
    kelasSiswa: 'XI-IPS-2',
    tanggal: '2026-06-29',
    jenis: 'Merusak Fasilitas Sekolah',
    poin: 30,
    catatan: 'Mencoret-coret tembok pembatas belakang sekolah dengan cat semprot.',
  },
  {
    id: 'p11',
    siswaId: 's5',
    namaSiswa: 'Eka Lestari',
    kelasSiswa: 'XII-IPA-2',
    tanggal: '2026-07-01',
    jenis: 'Atribut Seragam Tidak Lengkap',
    poin: 5,
    catatan: 'Tidak mengenakan dasi dan ikat pinggang hitam berlogo sekolah.',
  },
  {
    id: 'p12',
    siswaId: 's8',
    namaSiswa: 'Hendra Wijaya',
    kelasSiswa: 'X-B',
    tanggal: '2026-07-05',
    jenis: 'Merokok di Lingkungan Sekolah',
    poin: 50,
    catatan: 'Ditemukan korek dan rokok filter di tas sekolah saat razia rutin.',
  }
];

export const INITIAL_KEHADIRAN: Kehadiran[] = [
  {
    id: 'k1',
    siswaId: 's1',
    namaSiswa: 'Aditya Pratama',
    kelasSiswa: 'XI-IPA-1',
    alpa: 1,
    izin: 2,
    sakit: 1,
    diska: 0,
    persentaseKehadiran: 92,
    alpaConsecutive: 0,
  },
  {
    id: 'k2',
    siswaId: 's2',
    namaSiswa: 'Budi Santoso',
    kelasSiswa: 'XI-IPA-1',
    alpa: 4,
    izin: 1,
    sakit: 0,
    diska: 2,
    persentaseKehadiran: 86,
    alpaConsecutive: 1,
  },
  {
    id: 'k3',
    siswaId: 's3',
    namaSiswa: 'Cantika Putri',
    kelasSiswa: 'XI-IPS-2',
    alpa: 0,
    izin: 0,
    sakit: 0,
    diska: 0,
    persentaseKehadiran: 100,
    alpaConsecutive: 0,
  },
  {
    id: 'k4',
    siswaId: 's4',
    namaSiswa: 'Dedi Kurniawan',
    kelasSiswa: 'XI-IPA-1',
    alpa: 5, // Total 5 alpa
    izin: 1,
    sakit: 2,
    diska: 1,
    persentaseKehadiran: 82,
    alpaConsecutive: 3, // PENTING: alpa beruntun >= 3 hari memicu tanda merah di dashboard
  },
  {
    id: 'k5',
    siswaId: 's5',
    namaSiswa: 'Eka Lestari',
    kelasSiswa: 'XII-IPA-2',
    alpa: 0,
    izin: 3,
    sakit: 1,
    diska: 0,
    persentaseKehadiran: 94,
    alpaConsecutive: 0,
  },
  {
    id: 'k6',
    siswaId: 's6',
    namaSiswa: 'Farhan Ramadhan',
    kelasSiswa: 'XI-IPS-2',
    alpa: 2,
    izin: 0,
    sakit: 2,
    diska: 1,
    persentaseKehadiran: 90,
    alpaConsecutive: 0,
  },
  {
    id: 'k7',
    siswaId: 's7',
    namaSiswa: 'Gita Safitri',
    kelasSiswa: 'X-A',
    alpa: 0,
    izin: 1,
    sakit: 0,
    diska: 0,
    persentaseKehadiran: 98,
    alpaConsecutive: 0,
  },
  {
    id: 'k8',
    siswaId: 's8',
    namaSiswa: 'Hendra Wijaya',
    kelasSiswa: 'X-B',
    alpa: 1,
    izin: 1,
    sakit: 3,
    diska: 0,
    persentaseKehadiran: 91,
    alpaConsecutive: 0,
  }
];

export const INITIAL_BIMBINGAN: BimbinganLog[] = [
  {
    id: 'b1',
    siswaId: 's2',
    namaSiswa: 'Budi Santoso',
    kelasSiswa: 'XI-IPA-1',
    tanggal: '2026-06-18',
    jenisLayanan: 'Sosial',
    topik: 'Kasus Perundungan Siswa Lain',
    solusi: 'Siswa dimintai penjelasan dan diberikan bimbingan empati. Diberikan skorsing sementara sesuai aturan sekolah.',
    tindakLanjut: 'Pemantauan interaksi sosial siswa selama 2 minggu ke depan. Kerja sama dengan guru mata pelajaran.',
  },
  {
    id: 'b2',
    siswaId: 's1',
    namaSiswa: 'Aditya Pratama',
    kelasSiswa: 'XI-IPA-1',
    tanggal: '2026-06-25',
    jenisLayanan: 'Belajar',
    topik: 'Penurunan Konsentrasi dan Penggunaan HP saat Kelas',
    solusi: 'Menganalisis penyebab kecanduan game mobile. Menyepakati aturan penyerahan HP ke guru kelas saat KBM berlangsung.',
    tindakLanjut: 'Mengecek perbaikan nilai akademik pada ulangan tengah semester.',
  },
  {
    id: 'b3',
    siswaId: 's3',
    namaSiswa: 'Cantika Putri',
    kelasSiswa: 'XI-IPS-2',
    tanggal: '2026-07-01',
    jenisLayanan: 'Karir',
    topik: 'Kebingungan Memilih Jurusan Kuliah S1',
    solusi: 'Melakukan diskusi minat bakat dan menjelaskan kaitan program studi IPS dengan prospek kerja modern.',
    tindakLanjut: 'Memberikan materi brosur SNBP & SNBT serta link tes bakat online gratis.',
  },
  {
    id: 'b4',
    siswaId: 's4',
    namaSiswa: 'Dedi Kurniawan',
    kelasSiswa: 'XI-IPA-1',
    tanggal: '2026-07-04',
    jenisLayanan: 'Pribadi',
    topik: 'Masalah Kehadiran Beruntun dan Kehilangan Motivasi',
    solusi: 'Melakukan panggilan pribadi mendalam. Siswa mengaku membantu usaha warung makan orang tuanya hingga larut malam.',
    tindakLanjut: 'Mengadakan Home Visit atau memanggil orang tua siswa untuk mediasi pembagian waktu anak.',
  }
];

export const INITIAL_JADWAL: JadwalKonseling[] = [
  {
    id: 'j1',
    siswaId: 's4',
    namaSiswa: 'Dedi Kurniawan',
    tanggal: '2026-07-07',
    waktu: '09:00 - 10:00',
    jenis: 'Konseling',
    keterangan: 'Konseling lanjutan mengenai ketidakhadiran beruntun (3 hari alpa).',
    status: 'Terjadwal',
  },
  {
    id: 'j2',
    siswaId: 's2',
    namaSiswa: 'Budi Santoso',
    tanggal: '2026-07-08',
    waktu: '11:00 - 12:00',
    jenis: 'Konseling',
    keterangan: 'Evaluasi perilaku sosial setelah masa hukuman perundungan selesai.',
    status: 'Terjadwal',
  },
  {
    id: 'j3',
    siswaId: 's6',
    namaSiswa: 'Farhan Ramadhan',
    tanggal: '2026-07-09',
    waktu: '13:00 - 14:30',
    jenis: 'Home Visit',
    keterangan: 'Kunjungan rumah ke kediaman Bapak Syarif Ramadhan membicarakan penumpukan poin pelanggaran (80 poin).',
    status: 'Terjadwal',
  }
];
